<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>20d1a1d8-6ca3-44d9-b42f-56dd220aa26f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteDb.Distributed.Server\LiteDb.Distributed.Server.csproj" />
    <ProjectReference Include="..\LiteDb.Distributed.Studio\LiteDb.Distributed.Studio.csproj" />
  </ItemGroup>

</Project>
